from typing import Dict, Any
from pydantic import BaseModel, Field

class OptimizationResult(BaseModel):
    """
    Deterministic optimization metadata generated by the pipeline.
    Does not contain algorithmic sizing/rebalancing formulas.
    """
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    model_config = {"frozen": True}
