"""add_optimized_universe

Revision ID: 76af26206e39
Revises: aabaae224efd
Create Date: 2026-07-07 11:29:52.483642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76af26206e39'
down_revision: Union[str, None] = 'aabaae224efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimized_universes',
    sa.Column('optimized_universe_id', sa.String(length=36), nullable=False),
    sa.Column('parent_classified_universe_id', sa.String(length=36), nullable=False),
    sa.Column('previous_optimized_universe_id', sa.String(length=36), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('optimization_metrics', sa.JSON(), nullable=False),
    sa.Column('symbol_fingerprints', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_classified_universe_id'], ['classified_universes.classified_universe_id'], ),
    sa.PrimaryKeyConstraint('optimized_universe_id')
    )
    op.create_index(op.f('ix_optimized_universes_parent_classified_universe_id'), 'optimized_universes', ['parent_classified_universe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimized_universes_parent_classified_universe_id'), table_name='optimized_universes')
    op.drop_table('optimized_universes')
    # ### end Alembic commands ###
