"""Add LiquidityUniverseModel

Revision ID: f52271f26efa
Revises: 
Create Date: 2026-07-07 09:50:59.212336

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52271f26efa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidity_universes',
    sa.Column('liquidity_universe_id', sa.String(length=100), nullable=False),
    sa.Column('parent_snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('config_hash', sa.String(length=100), nullable=False),
    sa.Column('qualified_symbols', sa.JSON(), nullable=False),
    sa.Column('rejected_symbols', sa.JSON(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the record was last updated'),
    sa.PrimaryKeyConstraint('liquidity_universe_id', name=op.f('pk_liquidity_universes'))
    )
    op.create_index(op.f('ix_liquidity_universes_liquidity_universe_id'), 'liquidity_universes', ['liquidity_universe_id'], unique=False)
    op.create_index(op.f('ix_liquidity_universes_parent_snapshot_id'), 'liquidity_universes', ['parent_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidity_universes_parent_snapshot_id'), table_name='liquidity_universes')
    op.drop_index(op.f('ix_liquidity_universes_liquidity_universe_id'), table_name='liquidity_universes')
    op.drop_table('liquidity_universes')
    # ### end Alembic commands ###
