"""add_classifieduniversemodel

Revision ID: aabaae224efd
Revises: e2ab586f07b6
Create Date: 2026-07-07 10:50:31.066491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabaae224efd'
down_revision: Union[str, None] = 'e2ab586f07b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classified_universes',
    sa.Column('classified_universe_id', sa.String(length=100), nullable=False),
    sa.Column('parent_certified_universe_id', sa.String(length=100), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('config_hash', sa.String(length=100), nullable=False),
    sa.Column('classified_symbols', sa.JSON(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique identifier (UUID4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the record was last updated'),
    sa.Column('created_by', sa.String(), nullable=True, comment='Identity that created the record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='Identity that last updated the record'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for optimistic concurrency control'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classified_universes'))
    )
    op.create_index(op.f('ix_classified_universes_classified_universe_id'), 'classified_universes', ['classified_universe_id'], unique=False)
    op.create_index(op.f('ix_classified_universes_parent_certified_universe_id'), 'classified_universes', ['parent_certified_universe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_universes_parent_certified_universe_id'), table_name='classified_universes')
    op.drop_index(op.f('ix_classified_universes_classified_universe_id'), table_name='classified_universes')
    op.drop_table('classified_universes')
    # ### end Alembic commands ###
