"""add certification_reports

Revision ID: 8bb4c5ddd99b
Revises: 76af26206e39
Create Date: 2026-07-07 11:56:11.264779

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb4c5ddd99b'
down_revision: Union[str, None] = '76af26206e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_reports',
    sa.Column('certification_id', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('business_fingerprint_version', sa.String(), nullable=False),
    sa.Column('git_commit_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('functional_passed', sa.Boolean(), nullable=False),
    sa.Column('determinism_passed', sa.Boolean(), nullable=False),
    sa.Column('integrity_passed', sa.Boolean(), nullable=False),
    sa.Column('stress_passed', sa.Boolean(), nullable=False),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('test_results', sa.JSON(), nullable=False),
    sa.Column('determinism_results', sa.JSON(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('certification_id', name=op.f('pk_certification_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certification_reports')
    # ### end Alembic commands ###

