"""add_certifieduniversemodel

Revision ID: 60d36f3be3c8
Revises: f52271f26efa
Create Date: 2026-07-07 10:18:29.439916

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d36f3be3c8'
down_revision: Union[str, None] = 'f52271f26efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certified_universes',
    sa.Column('certified_universe_id', sa.String(), nullable=False),
    sa.Column('parent_snapshot_id', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('certified_symbols', sa.JSON(), nullable=False),
    sa.Column('rejected_symbols', sa.JSON(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('certified_universe_id', name=op.f('pk_certified_universes'))
    )
    op.create_index(op.f('ix_certified_universes_parent_snapshot_id'), 'certified_universes', ['parent_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certified_universes_parent_snapshot_id'), table_name='certified_universes')
    op.drop_table('certified_universes')
    # ### end Alembic commands ###
