"""add_managed_watchlist_snapshots_table

Revision ID: 7907f56b89f8
Revises: 5277f39712b8
Create Date: 2026-07-07 14:24:32.312125

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7907f56b89f8'
down_revision: Union[str, None] = '5277f39712b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_watchlist_snapshots',
    sa.Column('managed_snapshot_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fresh_snapshot_id', sa.String(), nullable=False),
    sa.Column('parent_fresh_watchlist_version', sa.Integer(), nullable=False),
    sa.Column('parent_candidate_watchlist_version', sa.String(), nullable=False),
    sa.Column('parent_universe_version', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('business_fingerprint', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fresh_snapshot_id'], ['fresh_watchlist_snapshots.freshness_snapshot_id'], name=op.f('fk_managed_watchlist_snapshots_fresh_snapshot_id_fresh_watchlist_snapshots')),
    sa.PrimaryKeyConstraint('managed_snapshot_id', name=op.f('pk_managed_watchlist_snapshots')),
    sa.UniqueConstraint('fresh_snapshot_id', name=op.f('uq_managed_watchlist_snapshots_fresh_snapshot_id'))
    )
    op.create_index(op.f('ix_managed_watchlist_snapshots_business_fingerprint'), 'managed_watchlist_snapshots', ['business_fingerprint'], unique=False)
    op.create_index(op.f('ix_managed_watchlist_snapshots_version'), 'managed_watchlist_snapshots', ['version'], unique=True)
    op.create_table('managed_watchlist_audit_records',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('managed_snapshot_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['managed_snapshot_id'], ['managed_watchlist_snapshots.managed_snapshot_id'], name=op.f('fk_managed_watchlist_audit_records_managed_snapshot_id_managed_watchlist_snapshots')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_managed_watchlist_audit_records'))
    )
    op.create_index(op.f('ix_managed_watchlist_audit_records_managed_snapshot_id'), 'managed_watchlist_audit_records', ['managed_snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_managed_watchlist_audit_records_managed_snapshot_id'), table_name='managed_watchlist_audit_records')
    op.drop_table('managed_watchlist_audit_records')
    op.drop_index(op.f('ix_managed_watchlist_snapshots_version'), table_name='managed_watchlist_snapshots')
    op.drop_index(op.f('ix_managed_watchlist_snapshots_business_fingerprint'), table_name='managed_watchlist_snapshots')
    op.drop_table('managed_watchlist_snapshots')
    # ### end Alembic commands ###
