"""add_liquidity_metrics

Revision ID: e2ab586f07b6
Revises: 60d36f3be3c8
Create Date: 2026-07-07 10:45:11.660440

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ab586f07b6'
down_revision: Union[str, None] = '60d36f3be3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidity_universes', sa.Column('liquidity_metrics', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liquidity_universes', 'liquidity_metrics')
    # ### end Alembic commands ###
