"""Add fresh_watchlist_snapshots table

Revision ID: 5277f39712b8
Revises: bf2304727c7f
Create Date: 2026-07-07 14:04:37.557525

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5277f39712b8'
down_revision: Union[str, None] = 'bf2304727c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fresh_watchlist_snapshots',
    sa.Column('freshness_snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('watchlist_snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('parent_candidate_watchlist_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When the record was last updated'),
    sa.ForeignKeyConstraint(['watchlist_snapshot_id'], ['watchlist_snapshots.snapshot_id'], name=op.f('fk_fresh_watchlist_snapshots_watchlist_snapshot_id_watchlist_snapshots')),
    sa.PrimaryKeyConstraint('freshness_snapshot_id', name=op.f('pk_fresh_watchlist_snapshots')),
    sa.UniqueConstraint('watchlist_snapshot_id', name=op.f('uq_fresh_watchlist_snapshots_watchlist_snapshot_id'))
    )
    op.create_index(op.f('ix_fresh_watchlist_snapshots_freshness_snapshot_id'), 'fresh_watchlist_snapshots', ['freshness_snapshot_id'], unique=False)
    op.create_index(op.f('ix_fresh_watchlist_snapshots_version'), 'fresh_watchlist_snapshots', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fresh_watchlist_snapshots_version'), table_name='fresh_watchlist_snapshots')
    op.drop_index(op.f('ix_fresh_watchlist_snapshots_freshness_snapshot_id'), table_name='fresh_watchlist_snapshots')
    op.drop_table('fresh_watchlist_snapshots')
    # ### end Alembic commands ###
