"""Add config_hash and lineage

Revision ID: 23e167e14404
Revises: d1e9f2a3b4c5
Create Date: 2026-07-07 13:27:28.093919

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e167e14404'
down_revision: Union[str, None] = 'd1e9f2a3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_snapshots', sa.Column('config_hash', sa.String(length=100), nullable=False))
    op.add_column('watchlist_snapshots', sa.Column('source_universe_snapshot_id', sa.String(length=100), nullable=True))
    op.add_column('watchlist_snapshots', sa.Column('source_universe_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_snapshots', 'source_universe_version')
    op.drop_column('watchlist_snapshots', 'source_universe_snapshot_id')
    op.drop_column('watchlist_snapshots', 'config_hash')
    # ### end Alembic commands ###
