"""Add candidate_selection_version

Revision ID: bf2304727c7f
Revises: 23e167e14404
Create Date: 2026-07-07 13:42:38.196904

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2304727c7f'
down_revision: Union[str, None] = '23e167e14404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_snapshots', sa.Column('candidate_selection_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_snapshots', 'candidate_selection_version')
    # ### end Alembic commands ###
