import hashlib
from datetime import datetime, timezone
from pydantic import BaseModel, Field

class CandidateVersion(BaseModel):
    """Versioning details for the candidate."""
    version: int = Field(default=1, description="Version of the candidate")
    model_config = {"frozen": True}

class CandidateMetadata(BaseModel):
    """Metadata surrounding the creation of the candidate."""
    created_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp when candidate was assembled")
    pipeline_version: str = Field(description="Pipeline version used to generate the candidate")
    strategy_versions: dict = Field(default_factory=dict, description="Versions of the individual strategies used")
    model_config = {"frozen": True}

class DetectionEvidence(BaseModel):
    """
    Descriptive evidence generated by detection stages.
    Must NOT contain quality, confidence, or scoring details.
    """
    support_break_detected: bool = Field(default=False, description="Whether a support break was detected")
    recovery_detected: bool = Field(default=False, description="Whether a recovery back above support was detected")
    false_break_validated: bool = Field(default=False, description="Whether the break was validated as false")
    trigger_reason: str = Field(default="", description="Description of the trigger criteria met")
    model_config = {"frozen": True}

class LiquidityGrabCandidate(BaseModel):
    """
    Immutable root entity representing a detected Liquidity Grab Candidate.
    """
    candidate_id: str = Field(description="Deterministic ID for this candidate")
    symbol_id: str = Field(description="Target symbol ID")
    timeframe: str = Field(description="Target timeframe")
    
    dataset_version: int = Field(description="Dataset version used")
    parent_trend_snapshot_version: int = Field(description="Parent Trend Snapshot version")
    parent_consolidation_snapshot_version: int = Field(description="Parent Consolidation Snapshot version")
    configuration_hash: str = Field(description="Hash of the configuration used")
    
    evidence: DetectionEvidence = Field(description="Evidence gathered during detection")
    metadata: CandidateMetadata = Field(description="Candidate metadata")
    version: CandidateVersion = Field(default_factory=CandidateVersion, description="Candidate version")

    @classmethod
    def generate_id(cls, symbol_id: str, dataset_version: int, trend_version: int, consolidation_version: int, config_hash: str) -> str:
        """
        Generates a deterministic Candidate ID from stable business inputs.
        """
        payload = f"{symbol_id}_{dataset_version}_{trend_version}_{consolidation_version}_{config_hash}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()
        
    model_config = {"frozen": True}
