from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, StrictInt, StrictFloat, ConfigDict
from backend.paper_fill_engine.models.pipeline import PipelineDiagnostics, PipelineTelemetry
from backend.paper_fill_engine.models.fill import FillState
from backend.paper_fill_engine.models.events import FillEvent

class PaperFillExecutionContext(BaseModel):
    """
    Immutable execution context defining the input boundaries for a fill simulation.
    No runtime state.
    """
    model_config = ConfigDict(frozen=True, extra="forbid")

    symbol: StrictStr = Field(..., description="The asset symbol (e.g. AAPL)")
    timeframe: StrictStr = Field(..., description="The execution timeframe (e.g. 1D, 1H)")
    dataset_version: StrictStr = Field(..., description="The dataset schema/version reference")
    parent_paper_order_snapshot_version: StrictStr = Field(..., description="Lineage reference to the paper order snapshot")
    
    configuration: Dict[str, Any] = Field(default_factory=dict, description="Configuration parameters for the fill")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Custom metadata for the fill")

class FillSimulationResult(BaseModel):
    """
    Immutable DTO produced by the DeterministicFillStage containing all simulated results.
    """
    model_config = ConfigDict(frozen=True, extra="forbid")
    
    fill_state: FillState = Field(..., description="The resulting fill state")
    fill_events: List[FillEvent] = Field(default_factory=list, description="Ordered list of simulated fills")
    total_filled_quantity: StrictInt = Field(default=0, description="Cumulative quantity filled")
    remaining_quantity: StrictInt = Field(..., description="Quantity left to be filled")
    average_fill_price: Optional[StrictFloat] = Field(default=None, description="Volume-weighted average price")

class PaperFillPipelineContext(BaseModel):
    """
    Mutable internal context for the pipeline.
    Never persisted into the final snapshot.
    """
    model_config = ConfigDict(extra="forbid")

    execution_context: PaperFillExecutionContext = Field(..., description="The validated execution context")
    
    # Generated by the deterministic fill simulation stage
    simulation_result: Optional[FillSimulationResult] = Field(default=None, description="The result of the fill simulation")
    
    diagnostics: PipelineDiagnostics = Field(default_factory=PipelineDiagnostics)
    telemetry: PipelineTelemetry = Field(default_factory=PipelineTelemetry)
