import logging
from typing import List, Optional
from backend.liquidity_grab_engine.detection.models.context import LiquidityGrabDetectionContext
from backend.liquidity_grab_engine.detection.models.models import DetectionEvidence, LiquidityGrabCandidate
from backend.liquidity_grab_engine.detection.pipeline.stages import ILiquidityGrabDetectionStage, CandidateAssemblyStage

logger = logging.getLogger(__name__)

class LiquidityGrabDetectionPipeline:
    """
    Deterministic detection pipeline.
    Executes detection stages and handles failure logic (fail fast).
    Finally runs Candidate Assembly.
    """
    def __init__(self, stages: List[ILiquidityGrabDetectionStage], assembly_stage: CandidateAssemblyStage):
        self.stages = stages
        self.assembly_stage = assembly_stage

    def execute(self, context: LiquidityGrabDetectionContext) -> Optional[LiquidityGrabCandidate]:
        logger.info("Starting Liquidity Grab Detection Pipeline.")
        
        evidence = DetectionEvidence()
        strategy_versions = {}
        
        for stage in self.stages:
            try:
                # If stage has a strategy with a version, record it
                if hasattr(stage, "strategy") and hasattr(stage.strategy, "version"):
                    stage_name = type(stage).__name__
                    strategy_versions[stage_name] = stage.strategy.version
                    
                evidence = stage.execute(context, evidence)
                # Fail fast logic (stop processing if a key condition is false, if configured to fail fast)
                # For simplicity, if pipeline fail_fast is enabled, we could break here,
                # but currently we run through all stages unless an exception occurs.
                if context.configuration.pipeline.fail_fast:
                    if not evidence.support_break_detected and type(stage).__name__ == 'SupportBreakDetectionStage':
                        logger.info("Failing fast: Support break not detected.")
                        break
                    if not evidence.recovery_detected and type(stage).__name__ == 'RecoveryDetectionStage':
                        logger.info("Failing fast: Recovery not detected.")
                        break
                    if not evidence.false_break_validated and type(stage).__name__ == 'FalseBreakValidationStage':
                        logger.info("Failing fast: False break not validated.")
                        break
            except Exception as e:
                logger.error(f"Stage {stage.__class__.__name__} failed: {str(e)}")
                raise
                
        candidate = self.assembly_stage.execute(context, evidence, strategy_versions)
        if candidate:
            logger.info(f"Candidate {candidate.candidate_id} successfully assembled.")
        else:
            logger.info("No valid candidate generated by pipeline.")
            
        return candidate
